Fix alignment of first port declaration
veripool/verilog-mode pull request #1771
Opened 2022-06-09 18:51 UTC by gmlarumbe

This PR fixes #1167 

It also changes the alignment of some variables on the following tests:
- autoinst_ams_vorwerk.v
- autoinst_protected.v
- autooutput_regexp.v
- autoreset_regin.v
- autosense_gifford.v
- autosense_venkataramanan_begin.v
- indent_directives.v
- indent_replicate.v
- params_multiline_msg618.v

To me it seems better alignment but there could be something I am missing about those tests.

Another thing is the mixture of tabs/spaces in the function `verilog-pretty-declarations`. Would it be a good idea to untabify it in a separate commit?

Cheers!

2022-06-12 14:36 UTC, wsnyder requested changes
Looks generally ok

For lines you change in the .el, please convert tabs to spaces.  (Using Emacs you can set indent-tabs-mode nil).  Ideally we'd have a makefile rule to do this but I haven't got around to it.

For lines you aren't functionally changing keep the tabs. Otherwise merging makes a mess as we need to be able to merge to/from Emacs master and a large untabify would cause difficulties.

When making the commit, use a comment that matches Emacs format.  Do a "make ChangeLog" then edit that, delete leading tabs, update, and use it as the comment (git commit -F ChangeLog)  The ChangeLog after editing for this one should look similar to this:

```
Fix alignment of first port declaration (#1771).

* verilog-mode.el (verilog-get-lineup-indent, verilog-pretty-declarations):
Fix alignment of first port declaration (#1771).
```

2022-06-12 14:36 UTC, wsnyder commented on verilog-mode.el
> +        )
I'm not sure this code needs a change, but if you do want to change it please upgrade to more standard format:

```suggestion
  (let ((m1 (make-marker))
        (e (point))
	(here (point))
	el r ind start startpos end endpos base-ind)
```

2022-06-12 20:27 UTC, gmlarumbe commented on verilog-mode.el
> +        )
Hi Wilson,

Thanks for the guidelines. I have updated the untabified lines and the commit message in bde31e6

2022-06-13 00:39 UTC, wsnyder approved these changes
Looks good - I approved you as a maintainer (congrats) so you can squash-merge this yourself!

2022-06-13 06:13 UTC, merged

2022-06-13 06:14 UTC, gmlarumbe commented
Thanks @wsnyder. I really appreciate it :)